library(Seurat)

### Data preparation for seurat pipeline

# 1. Load raw count data (Set the working directory to the folder where the matrix file is stored.)
# - Seurat has an easy function to load in data generated by CellRanger. This function will read the file into a single sparse matrix variable in R with genes as rownames and cell barcodes at colnames.

data <- Read10X_h5("single_cell/filtered_feature_bc_matrix.h5", use.names = TRUE, unique.features = TRUE)
# head(data)

# 1.1 Exploring the matrix
data[1:10, 1:10]
dim(data)

# 1.2 Check if the mitochondrial gene starts  from either **MT** or **mt**. This is very important as in later stages we will regress out few cells with high mitochondrial ratio. (If your mitochondrial genes are named differently, then you will need to adjust this pattern accordingly)
# 미토콘드리아의 비율을 확인하기 위해 (죽어가는 세포는 mt 비율 낮아짐)
# grep(pattern = "^MT-", x = rownames(x = data), value = TRUE)

mito.genes <- grep(pattern = "^mt-", x = rownames(x = data), value = TRUE)
mito.genes

## Move the data to "Seurat object"
# 2.1. Analyzing sc-RNA seq data is multi-step process once you start doing analysis, it can start getting messy if you start making dozens of other variables containing things like cell metadata, UMAP coordinates, etc.
# This issue is fixed by a special class of variable called a **Seurat object**. A seurat object serves essentially as an organized container to hold almost all types of data you will work with in scRNA-seq analysis. The two benefits of this are 1) it simply keeps everything more organized than managing dozens of independent R variables, and 2) it imposes "rules" that help prevent you from messing your data up (for example, it demands that the cells in your metadata table are an exact match with the cells in the expression matrix).

seurat.obj <- CreateSeuratObject(data)
View(seurat.obj@meta.data)

# There are three columns of information:

# **orig.ident**: This column will contain the sample identity if known.
# **nCount_RNA**: this column represents the number of UMIs per cell
# **nFeature_RNA**: this column represents the number of genes detected per cell


# 2.2. Examine QC metrics based on cell ranger html file (Can skip if not needed)
# a. Median UMI counts per cell
# b. Median Genes per cell

median(seurat.obj@meta.data$nCount_RNA) # 3333
median(seurat.obj@meta.data$nFeature_RNA)  # 1117

# 어떤 layer들이 있는지 확인
Layers(seurat.obj[["RNA"]])

# counts matrix 가져오기
counts_mat <- LayerData(seurat.obj, assay = "RNA", layer = "counts")
head(rownames(counts_mat))

## Quality control & Filtering
# Although the initial analysis using cell ranger has removed low-quality cells, further QC is crucial for high-quality scRNA data analysis. The expression matrix should be examined to;

# Commonly used QC metrics by the community include;
# **The number of genes detected in each cell**
# - low-quality cells or empty droplets will often have very few genes
# - cell doublets may exhibit an aberrantly high gene count

# **The percentage of reads that map to the mitochondrial genome**
# - low-quality / dying cells often exhibit extensive mitochondrial contamination


# 3.1 Add the mitochondrial percentage information
# - Seurat has a convenient function that allows us to calculate the proportion of transcripts mapping to mitochondrial genes.
# - The PercentageFeatureSet() function takes in a pattern argument and searches through all gene identifiers in the dataset for that pattern.
# - In our case we are searching for gene identifiers that begin with patter "mt".
# - For each cell, the function takes the sum of counts across all genes belonging to the "mt-" set, and then divides by the count sum for all genes. This value is multiplied by 100 to obtain a percentage value.
# - Higher % of mitochondrial gene indicates contamination from dead or dying cells

seurat.obj[["percent.mt"]] <- PercentageFeatureSet(seurat.obj, pattern = "^mt-")
View(seurat.obj@meta.data)
head(seurat.obj@meta.data)

# 3.2. Data visualization before QC
packageVersion("Seurat")
packageVersion("SeuratObject")

library(ggplot2)
library(tidyr)
library(dplyr)

# QC 필터링 전 meta.data를 long format으로 변환
meta_before_QC <- seurat.obj@meta.data %>%
  select(nFeature_RNA, nCount_RNA, percent.mt) %>%
  mutate(cell_id = rownames(seurat.obj@meta.data)) %>%
  pivot_longer(cols = c(nFeature_RNA, nCount_RNA, percent.mt),
               names_to = "feature", values_to = "value") %>%
  mutate(feature = factor(feature,
                           levels = c("nFeature_RNA", "nCount_RNA", "percent.mt")))

# QC 이전 violin plot
before_QC <- ggplot(meta_before_QC, aes(x = feature, y = value, fill = feature)) +
  geom_violin(scale = "width", trim = FALSE) +
  geom_jitter(width = 0.15, size = 0.1, alpha = 0.1) +
  facet_wrap(~ feature, scales = "free", ncol = 3) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    strip.text = element_text(face = "bold")
  ) +
  labs(
    title = "QC metrics — Before QC filtering",
    subtitle = paste0("n cells = ", ncol(seurat.obj)),
    x = NULL, y = NULL
  )

print(before_QC)

# Run this code only if you are curious about data
# **UMI counts (transcripts) per cell (nCount)**
# - The UMI counts per cell should be generally be above 500.

# nCount_RNA (UMI count per cell) density plot — Before QC filtering
nCount_density_before_QC <- seurat.obj@meta.data %>%
  ggplot(aes(x = nCount_RNA)) +
  geom_density(fill = "steelblue", alpha = 0.2) +
  scale_x_log10() +
  theme_classic() +
  ylab("Log10 cell density") +
  xlab("UMI counts per cell (log10 scale)") +
  ggtitle("nCount_RNA distribution — Before QC filtering") +
  geom_vline(xintercept = 500, color = "red", linetype = "dashed") +
  geom_vline(xintercept = 25000, color = "red", linetype = "dashed")

print(nCount_density_before_QC)

# **Genes detected per cell (nFeature_RNA)**
# - The UMI counts per cell should be generally be above 250.
seurat.obj@meta.data %>% 
  ggplot(aes(x=nFeature_RNA)) + 
  geom_density(alpha = 0.2) + 
  theme_classic() +
  scale_x_log10() + 
  geom_vline(xintercept = 250, color="red")+
  ylab("log 10 gene density") + xlab("Genes")

# 3.3. Quality control
seurat.obj <- subset(seurat.obj, subset = nFeature_RNA > 250 & nFeature_RNA < 2500 & percent.mt < 5)
dim(seurat.obj)
seurat.obj <- subset(seurat.obj, nCount_RNA >= 500 & nCount_RNA <= 20000)
dim(seurat.obj)

# QC 필터링 후 meta.data를 long format으로 변환
meta_after_QC <- seurat.obj@meta.data %>%
  select(nFeature_RNA, nCount_RNA, percent.mt) %>%
  pivot_longer(cols = c(nFeature_RNA, nCount_RNA, percent.mt),
               names_to = "feature", values_to = "value") %>%
  mutate(feature = factor(feature,
                           levels = c("nFeature_RNA", "nCount_RNA", "percent.mt")))

# QC 이후 violin plot
after_QC <- ggplot(meta_after_QC, aes(x = feature, y = value, fill = feature)) +
  geom_violin(scale = "width", trim = FALSE) +
  geom_jitter(width = 0.15, size = 0.1, alpha = 0.1) +
  facet_wrap(~ feature, scales = "free", ncol = 3) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    strip.text = element_text(face = "bold")
  ) +
  labs(
    title = "QC metrics — After QC filtering",
    subtitle = paste0("n cells = ", ncol(seurat.obj), " (before: 7699 → after: 7518)"),
    x = NULL, y = NULL
  )

after_QC

## Normalization 
# After removing unwanted cells from the dataset, the next step is normalizing the data. 
# - Why do we need to do? Different cells have different amount of mRNA(multiple reasons). Normalization step makes expression counts comparable across genes or samples.

# 4.1. By default, Seurat implements a global-scaling normalization method “LogNormalize” that normalizes the gene expression measurements for each cell by the total expression, multiplies this by a scale factor (10,000 by default), and log-transforms the result.

seurat.obj = NormalizeData(seurat.obj, normalization.method = "LogNormalize", scale.factor = 10000)

## Identification of highly variable genes
# Compared to doing the analysis with all the dataset working only with the highly variable genes highlights the biological signals.
# - Our main objective is to identify different cell types, however if we have 7000 rows and 10000 coloumns it will be very difficult. But it can be done by reducing the dimension based on PCA.
# - However most of the genes provide little information for e.g. housekeeping genes are expressed across cell types and using those genes it will be difficult to differentiate between Macrophage and NK cells.
# - By focusing only on genes with high variance, we can retain much of the structure of our data in as few as a couple thousand genes. 

seurat.obj = FindVariableFeatures(seurat.obj)### by default selection.method = "vst", nfeatures = 2000
top10 = head(VariableFeatures(seurat.obj), 10) ######## Identify the 10 most highly variable genes####
top10
#  [1] "Dcn"    "Sparc"  "S100a9" "Igfbp7" "Col3a1" "C1qb"   "Lyz2"   "Jchain"
#  [9] "Igkc"   "S100a8"

# Find variable is a function available within Seurat to identify the top 2000 genes for PCA analysis, UMPA/t-SNE, and clustering. To identify top variable genes, three methods can be selected
# Default - vst – Fits a line to the relationship of log(variance) and log(mean) using local polynomial regression. (Popular and mostly used).

# To visualize the data Seurat has a function VariableFeaturePlot 

plot1 = VariableFeaturePlot(seurat.obj)
LabelPoints(plot = plot1, points = top10, repel = TRUE)

#### Scaling: z-scores
# PCA works by identifying source of variation. We standardized the means and variance of our data using Z-score transformation. So every gene is considered equally and genes with higher average expression does not get weighed more in PCA.
# z-score

seurat.obj <- ScaleData(seurat.obj)

#### Perform linear dimensional reduction (PCA)
seurat.obj = RunPCA(seurat.obj, features = VariableFeatures(object = seurat.obj))

#### Determine the dimensionality of the dataset (Elbow plot)
ElbowPlot(seurat.obj, ndims = 50)

##### Cluster the cells
# Seurat uses a graph-based clustering approach using a K-nearest neighbor approach, and then attempts to partition this graph into highly interconnected communities. For more details refer https://satijalab.org/seurat/archive/v3.1/pbmc3k_tutorial.html;
# https://biocellgen-public.svi.edu.au/mig_2019_scrnaseq-workshop/clustering-and-cell-annotation.html

seurat.obj = FindNeighbors(seurat.obj, dims = 1:35, force.recalc = T)

#### To determine the resolution of clusters
# - We will use the FindClusters() function to perform the graph-based clustering.
# - The resolution is an important argument that sets the "granularity" of the downstream clustering and will need to be optimized for every individual experiment.
# - So generally a datasets of 3000-9000 cells the resolution set between 0.4-1.4 generally yields good clustering. Increased resolution values lead to a greater number of clusters, which is often required for larger datasets.
# - The clusters are saved in the seurat.obj@ident slot.

seurat.obj = FindClusters(seurat.obj, resolution = 0.6)

##### Run non-linear dimensional reduction (UMAP)
# - Seurat offers several non-linear dimensional reduction techniques, such as tSNE and UMAP, to visualize and explore these datasets. 
# - The goal of these algorithms is to learn the underlying manifold of the data in order to place similar cells together in low-dimensional space. 
# - These methods will require you to input number of PCA dimensions to use for the visualization, use the same number of PCs as input to the clustering analysis. 

seurat.obj = RunUMAP(object = seurat.obj, dims = 1:35)
DimPlot(object = seurat.obj, reduction = "umap", label = T, pt.size = 0.5, label.size = 5)

##### Run non-linear dimensional reduction (t-SNE) 
seurat.obj = RunTSNE(seurat.obj, reduction.use = "pca", dims.use = 1:35, do.fast = T)
p2 = TSNEPlot(seurat.obj)
p2

saveRDS(object = seurat.obj, file = paste0("single_cell/Seurat_Clustering.RDS"))
